version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: productos_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: productos_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://productos_mongo:27017/inventarioDB
      PORT: 5000
      JWT_SECRET: 123456789
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: productos_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
